version: "3.8"

services:
  emby-manager:
    image: 1524566636/emby-manager:latest
    container_name: emby-manager
    environment:
      - EMBY_URL=http://47.109.19.131:8116
      - EMBY_API_KEY=你的Emby_API_Key
    ports:
      - "8117:8000"
    restart: unless-stopped
